### ISSUE TITLE
get mapbox access token

### ISSUE THREAD

**Issue by jamisonvalentine** [UNCG-DAISY/StormImpactMap#11]

**Comment by jamisonvalentine** [comment]
https://account.mapbox.com/access-tokens

**Comment by ebgoldstein** [comment]
@jamisonvalentine — what do we need mapbox for?

**Comment by jamisonvalentine** [comment]
@ebgoldstein A lot of the examples and leaflet plugins I'm seeing use mapbox... I believe the template you suggested does under the hood as well. I'm not sure yet if it will be entirely necessary but I think mapbox has lots of tools already in place that we could make use of.
