### ISSUE TITLE
Add option to display prediction shapefile

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/StormImpactMap#15]
for a given storm, we might want to display the USGS prediction:

data available here as a shapefile:
https://coastal.er.usgs.gov/data-release/doi-P9Z362BC/

leaflet plugin for shapefiles:
https://github.com/calvinmetcalf/leaflet.shapefile

**Comment by ebgoldstein** [comment]
overwash extents are another optional layer to display, too:
https://coastal.er.usgs.gov/data-release/doi-P9BW6CG6/

**Comment by jamisonvalentine** [comment]
@ebgoldstein having issues using the leaflet plugin. error i'm getting:
![image](https://user-images.githubusercontent.com/47033011/92812103-0d760c80-f38d-11ea-9a13-fd015d7a148c.png)

Works with another shapefile(.zip) but not the ones provided by usgs

should I try this route?
https://gist.github.com/YKCzoli/b7f5ff0e0f641faba0f47fa5d16c4d8d

**Comment by jamisonvalentine** [comment]
@ebgoldstein disregard, making some progress

**Comment by ebgoldstein** [comment]
ok, so the shapefiles should have some sort of attribute in them that we might be able to color code...

I will figure out what that is...

**Comment by ebgoldstein** [comment]
from the metadata, the attribute is `POVW`, which varies from 0 to ~100. I think teh goal is to display those values.. maybe w/ a red/orange color ramp (near white for 0, and red/orange for 100)

<img width="451" alt="Screen Shot 2020-09-10 at 6 46 35 PM" src="https://user-images.githubusercontent.com/5330599/92818733-07d0f480-f396-11ea-89a9-c9df0eed0116.png">

**Comment by ebgoldstein** [comment]
I'm not sure how to get an attribubte of a `shp` to color the line... but that is the goal.. make sense @jamisonvalentine ?

**Comment by jamisonvalentine** [comment]
it does, i'll see if I can get that to work now

**Comment by jamisonvalentine** [comment]
really quick before I dig in, do you know where I can find the respective values for that attribute?

**Comment by jamisonvalentine** [comment]
I think I see now. It's in the dbf file... just need to figure out how to parse

**Comment by ebgoldstein** [comment]
yeah totally... there should be a way to color the shapefile based on its `.dbf`

**Comment by jamisonvalentine** [comment]
@ebgoldstein have a few different things going on here which I will clean up, but for now:

- shapefiles are color coded (went w/ yellow instead of white just for visibility for the time being, feel free to change whenever)
- included overwash extent shapefiles (not color coded)
- added option to display markers from csv sample data in the Control

**Comment by ebgoldstein** [comment]
Super Excellent! its all there! (background map, NOAA tiles, USGS Pred., USGS Obs., and ML Obs.)

- yellow to red color ramp is great
- overwash extent does not need to be color coded

Ideas:
perhaps have section breaks for each type of data layer (background, NOAA tiles, USGS Pred., USGS Obs., and ML Obs.)?
(the the horizontal lines below)
<img width="280" alt="Screen Shot 2020-09-11 at 8 30 19 AM" src="https://user-images.githubusercontent.com/5330599/92925811-0ee51a80-f409-11ea-83f6-b70378626ab1.png">

Also, maybe a slider for the ML observations, for 0-1..  something like this? :
<img width="330" alt="Screen Shot 2020-09-11 at 8 36 07 AM" src="https://user-images.githubusercontent.com/5330599/92926340-dc87ed00-f409-11ea-920f-1c0ab57cc8ad.png">

**Comment by ebgoldstein** [comment]
I think the slider is probably a bad idea, actually...

**Comment by jamisonvalentine** [comment]
@ebgoldstein safe to close?

**Comment by ebgoldstein** [comment]
yeah, esp. since you just reopened https://github.com/UNCG-DAISY/StormImpactMap/issues/19.
