### ISSUE TITLE
mockup/wireframe for website

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/StormImpactMap#16]
Main things i think we need:
- a title
- the map
- an acknowledgement on the map of where the data comes from.
- a note saying this is an experimental product and we are not liable.
- a header or drawer with:
  - an 'about' for the project 
  - contact page to get in touch with you and me
  - a link back to the github repo.
  - a way to select storm images to display
  - a way to select if markers are displayed
  - a way to select if forecasts (https://github.com/UNCG-DAISY/StormImpactMap/issues/15) are diplayed

**Comment by jamisonvalentine** [comment]
planning on trying 2 different layout implementations

a) Header only
b) Header (navbar) + drawer (sidebar)

**Comment by jamisonvalentine** [comment]
also need to decide on color scheme

**Comment by jamisonvalentine** [comment]
refer to https://storms.ngs.noaa.gov/storms/laura/index.html#6/28.324/-89.363
for inspiration

**Comment by ebgoldstein** [comment]
also, @jamisonvalentine , i was thinking... we may want our site to look radically different from NOAA's site to avoid any confusion. Things like:

1. use a different basemap (i.e., like the stamen #toner-lite : http://maps.stamen.com/#toner-lite/12/37.7706/-122.3782)
2. Pick a layout where the buttons/elements are in a drawer (vs a header like the NOAA page...)
3. have a different color scheme.

**Comment by jamisonvalentine** [comment]
@ebgoldstein sounds good. Would you rather have a layout/interface similar to the Coastal Image Labeler?

**Comment by ebgoldstein** [comment]
I see positives and negatives to that idea...  but I think i prefer to leave it to you to decide. is that ok?

**Comment by jamisonvalentine** [comment]
absolutely, I'll be brainstorming, researching, and prototyping different layouts to try and I'll get your feedback along the way

**Comment by jamisonvalentine** [comment]
@ebgoldstein how do you feel about this drawer/sidenav design?

https://awardonline.com/awards/award-annuals

**Comment by jamisonvalentine** [comment]
@ebgoldstein here's a very basic attempt at it where clicking on the About or Contact links display a modal. Do you think this is still okay or would you rather have those links direct user to an entire different page?

https://uncg-daisy.github.io/StormImpactMap/layouts/sidenav.html

**Comment by ebgoldstein** [comment]
this looks good. Let's go with the Pop-up for now

**Comment by ebgoldstein** [comment]
this is a new coastal website... just dropping it here in case it has some useful design ideas: https://blueearthdata.org/

**Comment by ebgoldstein** [comment]
folded into https://github.com/UNCG-DAISY/StormImpactMap/issues/27
