### ISSUE TITLE
Provide way for users to be able to interact w/ data

### ISSUE THREAD

**Issue by jamisonvalentine** [UNCG-DAISY/StormImpactMap#20]
- user should be able to accept/reject washover prediction for images from inference model
_may be implemented as yes/no question in marker popup_

**Comment by ebgoldstein** [comment]
in the simplest version of this interactivity, there is text in the marker that says 'Hey, there is no washover here!', which is a link. Clicking on that link autofills a private Google sheet with some info:

- data from the csv about that marker (storm name, archive name, WashPred) 
- and a datetime saying when someone clicked that link

each row of the sheet then tells us that someone doesn't agree with one of our predictions, which image the person doesn't agree with, when they disagreed.

**Comment by ebgoldstein** [comment]
hey @ShahNafisRafique, I'm looping you into this issue to ask a Q:

@jamisonvalentine is building an [interactive map](https://uncg-daisy.github.io/StormImpactMap/) using the NOAA images (using the webtiles). On this map there will be markers at certain locations. These markers signify that the ML model sees something in an image at this location. Is there a way that we can call specific (compressed) images from the VM via the  Coastal Image Labeler ? i.e., get a URL for a specific image?  

in the ideal world, when someone clicks the marker it shows the data about the image (see below), but also a small version of the actual image (imagine a small picture below in the pop up after all that text info):

<img width="924" alt="Screen Shot 2020-09-15 at 12 06 57 PM" src="https://user-images.githubusercontent.com/5330599/93235780-01eb6280-f74c-11ea-8728-fc1560ab9c03.png">

here is the actual image, S21767526.jpg:

![S21767526_small](https://user-images.githubusercontent.com/5330599/93247359-32d39380-f75c-11ea-80da-d94f2ab618b3.jpg)

**Comment by ShahNafisRafique** [comment]
@ebgoldstein 

If you just want a specific image, like the jpg or whatever type it is, you can get the image based of the `_id` from MongoDB.

For example heres an image from Florence
![5f5c1c37016e86108aec3c66](https://user-images.githubusercontent.com/38015120/93271160-9a033f00-f780-11ea-9e73-b91f1dcb050b.jpg)
With its URL being either 

[https://coastalimagelabeler.science/api/image/show/Compressed/5f5c1c37016e86108aec3c66](https://coastalimagelabeler.science/api/image/show/Compressed/5f5c1c37016e86108aec3c66) for compressed or 

[https://coastalimagelabeler.science/api/image/show/Original/5f5c1c37016e86108aec3c66](https://coastalimagelabeler.science/api/image/show/Original/5f5c1c37016e86108aec3c66) for the original.

**Comment by ebgoldstein** [comment]
rad — thx @ShahNafisRafique .

@jamisonvalentine — i will add a column to the `csv` for the hash of each image... so then a small thumbnail of each image could be displayed in the marker bubble, if we want.. 

- [x] add image hash to `csv` for Florence, Michael, and Isaias

**Comment by ebgoldstein** [comment]
ok, as of https://github.com/UNCG-DAISY/StormImpactMap/commit/6f62d0a86f33ce89c40cddd4e4ea04ea82b2e38f the image hash is now included in the 3 `csv` files (column is`_id`). @jamisonvalentine — one option is now to show the actual image in the marker...
I recommend using the compressed route so the link would be:


`'https://coastalimagelabeler.science/api/image/show/Compressed/' + '_id'`

**Comment by jamisonvalentine** [comment]
@ebgoldstein 
1) it looks like the csv's now have an extra unintentional column added to the front
![image](https://user-images.githubusercontent.com/47033011/93688834-f45d1200-fa96-11ea-8374-5a7ed2a10673.png)

2) I added thumbnails of the images to the popups but it seems to be causing just a bit of lag (not sure if it's significant enough to be a problem). would you rather keep things this way or would you prefer a button/link to open the associated image in a new tab?

**Comment by ebgoldstein** [comment]
oh wow that lag is bad for me... And i see the VM with the images getting hit w/ requests:

<img width="371" alt="Screen Shot 2020-09-19 at 5 02 29 PM" src="https://user-images.githubusercontent.com/5330599/93689165-eeb4fb80-fa99-11ea-9ae3-bf183df45101.png">

but for now just a link to open a new page w/ the image is totally fine.... 
(we can brainstorm other ideas too)..

and I'll remove the extra column in the csv... must have added it inadvertently doing the join in pandas... 

**edit**: done via https://github.com/UNCG-DAISY/StormImpactMap/commit/f093c426806f5c60afde124af2f47febaf65ae4d

**Comment by ebgoldstein** [comment]
@ShahNafisRafique : 

If a random person (without a Labeler account) looks at the Storm map and sees this marker:

<img width="468" alt="Screen Shot 2020-09-20 at 5 28 07 PM" src="https://user-images.githubusercontent.com/5330599/93722702-be875e80-fb66-11ea-9630-3702d5a4660a.png">

if they click on the 'View Image' button, they get set to this url: https://coastalimagelabeler.science/api/image/show/Compressed/5f5c1c1b016e86108aebb8b6

I am wondering if they can be sent directly to the labeler for that image? in other words, given an image (the hash), am I correct that there is no way for someone to be allowed to **label** the image w/o an account and w/o being assigned to that catalog?

**Comment by ShahNafisRafique** [comment]
@ebgoldstein They would need to have permissions to tag that catalog and have an account. If they have both then we can make a API where we can assign a specific image to a user, or make a new entry in the `assignedImages` table.

**Comment by ebgoldstein** [comment]
ok — good to know... (thx @ShahNafisRafique)...

**Comment by ebgoldstein** [comment]
cool.. i can see the pics in the markers now (from the last commit https://github.com/UNCG-DAISY/StormImpactMap/commit/efa35882d384d45c2ae821ce44cb3f6405909c32).

you probably already saw this/know this @jamisonvalentine: 
I still think this implementation is grabbing all the pictures when the site opens, vs. only pulling a single picture when a marker is opened... see the example below and the 'waiting for/transferring data' message on the bottom left.

<img width="592" alt="Screen Shot 2020-09-21 at 1 17 11 PM" src="https://user-images.githubusercontent.com/5330599/93799373-15477380-fc0d-11ea-812c-4256c4edd7bd.png">

**Comment by jamisonvalentine** [comment]
@ebgoldstein  working on different ways to handle this scenario... how would you feel about having a "View Image" button in the pop that will then add a clickable thumbnail?

**Comment by ebgoldstein** [comment]
I think that a button to activate the clickable thumbnail is a good work around.

One option is that the clickable thumbnail opens a new page. On that new page the user is shown the image (from the coastal image labeler API) and asked the Q: 'Do you see washover in this image?'. The user's yes/no answer is then sent to a DB...

**Comment by ebgoldstein** [comment]
ok, an update... there has been a change to the coastal image labeler API.. 

https://github.com/UNCG-DAISY/Coastal-Image-Labeler/issues/157#issuecomment-699518766

Edit: ~~the old API still works, so the URLs currently in the map still work, but should be modified eventually...~~ i added the new endpoint via https://github.com/UNCG-DAISY/StormImpactMap/commit/4f3b57ab820422a964e07d51f0813857f9ac7fd4

**Comment by ebgoldstein** [comment]
ok, new endpoints are working on the VM... so it's all back to where it was

**Comment by ebgoldstein** [comment]
I'm going to close this long issue and collapse it down... its getting loooong. https://github.com/UNCG-DAISY/StormImpactMap/issues/29
