### ISSUE TITLE
Implement Contact Modal

### ISSUE THREAD

**Issue by jamisonvalentine** [UNCG-DAISY/StormImpactMap#24]
Include ways to get in touch with creators/contributors (Evan and Jamison)

**Comment by ebgoldstein** [comment]
(brain zap, sorry (for above)..)

**Comment by ebgoldstein** [comment]
see this as example of potential info to include: https://uncg-daisy.github.io/Coastal-Image-Labeler/docs/contactUs

**Comment by jamisonvalentine** [comment]
not complete but closing this and #23 to reduce clutter
