### ISSUE TITLE
flesh out sidenav drawer

### ISSUE THREAD

**Issue by jamisonvalentine** [UNCG-DAISY/StormImpactMap#27]
- [x] make collapsible
- [x] hightlight link on hover
- [x] change menu items font
- [x] add icons
- [x] animated menu button:
https://www.w3schools.com/howto/howto_css_menu_icon.asp

**Comment by ebgoldstein** [comment]
I'm folding the stray tasks from https://github.com/UNCG-DAISY/StormImpactMap/issues/16 into this issue:

- [x] liability statement (i can write this)
- [x] a link back to the github repo 
- [x] acknowledgement where NOAA +USGS + ML data comes from (i can write this)

**Comment by jamisonvalentine** [comment]
will open separate issue to improve appearance of modal content
