### ISSUE TITLE
DB connection for user data from markers

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/StormImpactMap#29]
There are three ideas re: DB connection (increasing in complexity):
- google sheet
- firebase
- spin up a VM

**Comment by jamisonvalentine** [comment]
@ebgoldstein google sheets implementation working now on new-features branch

clicking the No Washover button appends a new row to the sheet https://docs.google.com/spreadsheets/d/1bdSj2dumlruTfk7jQBNor_3ei0Y3PXeIfCoxlwWgIzE/edit#gid=0

used storm, archive, image, and id columns just to test
let me know which columns would actually be best to use and I'll update

**Comment by ebgoldstein** [comment]
that is great!

- I would change the name of the google sheet to 'Washover False Positives'
- The only column i would add is the prediction score
- feel free to do a PR with the main branch (i think the main branch is a few commits ahead re: the storm track)

**Comment by ebgoldstein** [comment]
i think for now, a sheet is totally fine... My current thinking is that the button should eventually just send folx  to the Coastal image labeled... that discussion is here:

https://github.com/UNCG-DAISY/Coastal-Image-Labeler/issues/165

**Comment by ebgoldstein** [comment]
@jamisonvalentine — so i think once the branch with the sheet is pulled into the master branch, this issue can be closed for now
