### ISSUE TITLE
Marker popup and user interaction

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/StormImpactMap#30]
user should be able to accept/reject washover prediction for images. there are two implementation ideas:
-  implemented as yes/no question in marker popup
-  implemented on a new page. Button in marker popup leads to a new page where user is shown the image (from the coastal image labeler API) and asked the Q: 'Do you see washover in this image?'. The user's yes/no answer is then sent to a DB...

The map has a link in the markers that sends users to an API of the original image.  
There is now another relevant API endpoint: `/gradcam`

https://github.com/UNCG-DAISY/StormImpactMap/blob/3823087628cacef6be7dd1c792229f6940f83b8a/js/popups.js#L1-L3

Can we have a second link in the marker, under 'View Image' called 'View ML Results' that sends a user to the `/gradcam` endpoint?

**Comment by jamisonvalentine** [comment]
@ebgoldstein not sure if this is the method I'll end up going with but it looks like this can be done using windows.sessionStorage (stores small amount of data in the browser)... I'll research other ways, but my first solution is to create another another endpoint ("imageviewer") and use local storage to pass the image url

**Comment by jamisonvalentine** [comment]
this is pretty much the skeleton for the image viewer for now... will try to spend more time on it tomorrow

![image](https://user-images.githubusercontent.com/47033011/94494721-d5106400-01bd-11eb-91db-920bdba769bc.png)

**Comment by ebgoldstein** [comment]
this is great!

**Comment by ebgoldstein** [comment]
also, if you use the `/compressed` endpoint (as `im_type`) for the coastal image labeler, its a smaller jpg..

https://github.com/UNCG-DAISY/StormImpactMap/blob/6822f3141cd6d1e921301a32e886887e25f55e53/js/popups.js#L1-L2

**Comment by jamisonvalentine** [comment]
gradcam link should be there now too

**Comment by jamisonvalentine** [comment]
> this is great!
> 
> Also, could you use an iframe?

great point, didn't think about that. I'll see if that works better

**Comment by ebgoldstein** [comment]
one option, just to make it easy for now (and not require sessions storage/iframe) is that each marker has 3 links:
- a link to the original image (`/original`)
- a link to the gradcam image (`/gradcam`)
- a link to the yes/no question (and eventually use your wireframe and put the picture in)

**Comment by ebgoldstein** [comment]
(I reorganizes the issues... this issue is focused on the markers and interaction... the other issue (#29 )  is focused on the connection to the DB to record the interactions )

**Comment by jamisonvalentine** [comment]
> one option, just to make it easy for now (and not require sessions storage/iframe) is that each marker has 3 links:
> 
> * a link to the original image (`/original`)
> * a link to the gradcam image (`/gradcam`)
> * a link to the yes/no question (and eventually use your wireframe and put the picture in)

I may not be picturing this idea the right way but I believe adding a link to the yes/no question (I'm assuming you mean in a new tab) seems like it might be difficult to do without using some sort of storage or an iframe. The problem that I'm having is with communicating/using the same data across 2 separate endpoints

....
just realized it's probably not that difficult after all (I think). @ebgoldstein do you want all 3 links to open to separate pages or all on the same one?

**Comment by jamisonvalentine** [comment]
@ebgoldstein looking up ways in incorporate zoomable images... haven't found anything that's really promising but I'll post ideas here
http://imgix.github.io/drift/
https://uncg-daisy.github.io/StormImpactMap/testviewer.html
https://uncg-daisy.github.io/StormImpactMap/testmodal.html

**Comment by ebgoldstein** [comment]
the zoom on hover is a v. neat idea. 
Regarding markers and links, this is what exists now:

<img width="300" alt="Screen Shot 2020-09-30 at 8 32 21 AM" src="https://user-images.githubusercontent.com/5330599/94687099-ba430a00-02f9-11eb-8570-6237585c2ad3.png">

I imagine there could be 2 versions we think about:

V1 is just all the links in the markers like it is now... but maybe one more link/button below the existing links that says: 
"Report there is no overwash in the images linked above"
this just requires a new link/button being added, and that link/button writes to a DB

V2 is the marker has a single link, which opens a new page for users. That single new page has the 2 pictures (maybe zoom feature), and a button allowing users to "Report there is no overwash in the images". that button writes to the DB

I think V2 would be the best (in terms of clicks), but i imagine V1 is easier..

regardless — Right now, the map is so so good that my suggestion is you start a new code branch to work on these ideas, so this version of the map remains visible/working in the interim.

**Comment by ebgoldstein** [comment]
I have been thinking... i think we should pursue the v2 idea above (separate page) and also this new page could allow users to look at the next/previous image (in geographic space)..

**Comment by ebgoldstein** [comment]
i think we can close this for now...
