### ISSUE TITLE
Add Hurricane Track

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/StormImpactMap#32]
Hurricane tracks could be a check box just like other data..

https://www.nhc.noaa.gov/data/tcr/

**Comment by ebgoldstein** [comment]
These are `.shp` files, but the website also has `kmz` versions.. 
I put Florence (`al04*`) and Michael (`al14*`) in the `/data` folder.. Isaias has not been released yet..

the `*_lin.shp` file is the one we want..

**Comment by ebgoldstein** [comment]
I added Dorian too (`al05*`)

**Comment by jamisonvalentine** [comment]
hurricane tracks in the map now, is this what you had in mind? any changes I should make?

**Comment by ebgoldstein** [comment]
I think I prefer it to be just a line

**Comment by ebgoldstein** [comment]
and I think the map now is showing the line, point, wind radii and windswath

**Comment by ebgoldstein** [comment]
I have an idea...

**Comment by ebgoldstein** [comment]
Ok, rad — this is it.. 

i removed the  other `shp` files from zip...

<img width="1104" alt="Screen Shot 2020-10-03 at 8 24 26 PM" src="https://user-images.githubusercontent.com/5330599/95004231-85171000-05b6-11eb-8078-182ae53205d9.png">

I just need to remember to remove the point, wind radii, and windswath from the  zip

**Comment by ebgoldstein** [comment]
this map is hot
