### ISSUE TITLE
display a leaflet map with NOAA images (Via web map tiles — WMTS)

### ISSUE THREAD

**Issue by jamisonvalentine** [UNCG-DAISY/StormImpactMap#5]

**Comment by jamisonvalentine** [comment]
@ebgoldstein a few questions here:

1) should I be using a certain map as a base, then overlaying images/markers on top of that?
2) where do I find the actual NOAA images or tilesets to use for this specific project?

**Comment by ebgoldstein** [comment]
I think a normal open street basemap is fine... I think eventually we want the tiles from NOAA.

**Comment by jamisonvalentine** [comment]
2020 NOAA Tilesets

https://storms.ngs.noaa.gov/storms/tileso/services/tileserver.php

**Comment by ebgoldstein** [comment]
!!!! Super Nice @jamisonvalentine !!!

<img width="768" alt="Screen Shot 2020-08-28 at 5 21 53 PM" src="https://user-images.githubusercontent.com/5330599/91616070-fc6fd900-e952-11ea-8257-00fdb132941e.png">
