### ISSUE TITLE
make markers clickable, with the name of the image and storm/archive info appearing in a bubble if marker is clicked

### ISSUE THREAD

**Issue by jamisonvalentine** [UNCG-DAISY/StormImpactMap#8]

**Comment by jamisonvalentine** [comment]
@ebgoldstein where will I get name of image and storm info from?

**Comment by ebgoldstein** [comment]
The name of the storm is just the name of the csv file... 
the image name, and the flight date/name (from NOAA) is something that i need to add to the csv. I will reupload a csv with that info..

- [x] add 'image name' column and 'flight name/date' column to csv file.

**Comment by ebgoldstein** [comment]
added via https://github.com/UNCG-DAISY/StormImpactMap/commit/46d864c0b5aa959fda041e850e3ba4e86730e36c

**Comment by jamisonvalentine** [comment]
@ebgoldstein just noticed the order for the coordinates in the Isaias csv is reversed

**Comment by jamisonvalentine** [comment]
![image](https://user-images.githubusercontent.com/47033011/93114685-e10e0900-f688-11ea-9baa-adc290e49519.png)

**Comment by jamisonvalentine** [comment]
or maybe the other files are... which would you say is the correct order?

**Comment by ebgoldstein** [comment]
I think the order should not matter... and should not impact the actual latitude and Longitude values..

**Comment by jamisonvalentine** [comment]
would it be a difficult to reverse the order in the isaias csv in order to avoid writing code for special cases? The code so far is expecting the order in the michael and florence samples

**Comment by ebgoldstein** [comment]
done

**Comment by ebgoldstein** [comment]
this is done, and wrapped into the discussion in #20
